branches:
    only:
        - master

language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

before_script:
    - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then phpenv config-rm xdebug.ini; fi;
    - composer --no-interaction --prefer-source install

script:
    - bin/phpspec run -f dot
